{
 "title": "Prediction Drift",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model Performance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select key, value, TO_TIMESTAMP(timestamp / 1000) as date\nfrom mlflow.latest_metrics;"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Share of Missing Values",
   "type": "trend",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select month::int, share_missing_values from grafana.evidently_metrics;"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "select month, num_drifted_columns from grafana.evidently_metrics;"
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "select month, prediction_drift\nFROM grafana.evidently_metrics;"
    }
   ]
  },
  {
   "title": "Pipeline Runs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select * from magic.pipeline_run;"
    }
   ]
  }
 ]
}