apiVersion: 1
groups:
    - orgId: 1
      name: data_quality
      folder: bank_marketing
      interval: 10s
      rules:
        - uid: dds363bqqgkxsd
          title: prediction_drift
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PCC52D03280B7034C
              model:
                editorMode: code
                format: table
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: select prediction_drift from grafana.evidently_metrics where prediction_drift > 0.1;
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 20s
          annotations:
            summary: prediction drift detected
          labels:
            app: bank_marketing
            service: prediction
          isPaused: false
          notification_settings:
            receiver: webhook
